export const available = [
  {
    id: 0,
    type: "information",
    text: "Messengers",
    totalInLine: 2,
    columntotal: 2,
    blocks: [
      {
        social: "whatsapp",
        imageUrl: "/icons/whatsapp.svg",
        link: "https://instagram.com/pounes.ir",
        text: "My WhatsApp",
      },
      {
        social: "telegram",
        imageUrl: "/icons/telegram.svg",
        link: "https://t.me/pounes_irr",
        text: "My Telegram",
      },
      {
        social: "bale",
        imageUrl: "/icons/bale.svg",
        link: "https://t.me/pounes_irr",
        text: "My Bale",
      },
      {
        social: "soroush",
        imageUrl: "/icons/soroush.svg",
        link: "https://t.me/pounes_irr",
        text: "My Soroush",
      },
      {
        social: "discord",
        imageUrl: "/icons/discord.svg",
        link: "https://t.me/pounes_irr",
        text: "My Discord",
      },
      {
        social: "skype",
        imageUrl: "/icons/skype.svg",
        link: "https://t.me/pounes_irr",
        text: "My Skype",
      },
      {
        social: "messenger",
        imageUrl: "/icons/messenger.svg",
        link: "https://t.me/pounes_irr",
        text: "My Messenger",
      },
      {
        social: "kik",
        imageUrl: "/icons/kik.svg",
        link: "https://t.me/pounes_irr",
        text: "My Kik",
      },
      {
        social: "viber",
        imageUrl: "/icons/viber.svg",
        link: "https://t.me/pounes_irr",
        text: "My Viber",
      },
      {
        social: "line",
        imageUrl: "/icons/line.svg",
        link: "https://t.me/pounes_irr",
        text: "My Line",
      },
      {
        social: "eitaa",
        imageUrl: "/icons/eitaa.svg",
        link: "https://t.me/pounes_irr",
        text: "My Eitaa",
      },
      {
        social: "gap",
        imageUrl: "/icons/gap.svg",
        link: "https://t.me/pounes_irr",
        text: "My Gap",
      },
    ],
  },
  {
    id: 1,
    type: "messenger",
    text: "Messengers",
    totalInLine: 2,
    columntotal: 2,
    blocks: [
      {
        social: "whatsapp",
        imageUrl: "/icons/whatsapp.svg",
        link: "https://instagram.com/pounes.ir",
        text: "My WhatsApp",
      },
      {
        social: "telegram",
        imageUrl: "/icons/telegram.svg",
        link: "https://t.me/pounes_irr",
        text: "My Telegram",
      },
      {
        social: "bale",
        imageUrl: "/icons/bale.svg",
        link: "https://t.me/pounes_irr",
        text: "My Bale",
      },
      {
        social: "soroush",
        imageUrl: "/icons/soroush.svg",
        link: "https://t.me/pounes_irr",
        text: "My Soroush",
      },
      {
        social: "discord",
        imageUrl: "/icons/discord.svg",
        link: "https://t.me/pounes_irr",
        text: "My Discord",
      },
      {
        social: "skype",
        imageUrl: "/icons/skype.svg",
        link: "https://t.me/pounes_irr",
        text: "My Skype",
      },
      {
        social: "messenger",
        imageUrl: "/icons/messenger.svg",
        link: "https://t.me/pounes_irr",
        text: "My Messenger",
      },
      {
        social: "kik",
        imageUrl: "/icons/kik.svg",
        link: "https://t.me/pounes_irr",
        text: "My Kik",
      },
      {
        social: "viber",
        imageUrl: "/icons/viber.svg",
        link: "https://t.me/pounes_irr",
        text: "My Viber",
      },
      {
        social: "line",
        imageUrl: "/icons/line.svg",
        link: "https://t.me/pounes_irr",
        text: "My Line",
      },
      {
        social: "eitaa",
        imageUrl: "/icons/eitaa.svg",
        link: "https://t.me/pounes_irr",
        text: "My Eitaa",
      },
      {
        social: "gap",
        imageUrl: "/icons/gap.svg",
        link: "https://t.me/pounes_irr",
        text: "My Gap",
      },
    ],
  },
  {
    id: 12,
    type: "socialmedia",
    text: "Social Media",
    totalInLine: 2,
    columntotal: 2,
    blocks: [
      {
        social: "telegram",
        imageUrl: "/icons/telegram.svg",
        link: "https://instagram.com/pounes.ir",
        text: "Telegram Channel",
      },
      {
        social: "instagram",
        imageUrl: "/icons/instagram.svg",
        link: "https://t.me/pounes_irr",
        text: "Instagram",
      },
      {
        social: "youtube",
        imageUrl: "/icons/youtube.svg",
        link: "https://t.me/pounes_irr",
        text: "YouTube",
      },
      {
        social: "aparat",
        imageUrl: "/icons/aparat.svg",
        link: "https://t.me/pounes_irr",
        text: "Aparat",
      },
      {
        social: "twitter",
        imageUrl: "/icons/twitter.svg",
        link: "https://t.me/pounes_irr",
        text: "Twitter",
      },
      {
        social: "linkedin",
        imageUrl: "/icons/linkedin.svg",
        link: "https://t.me/pounes_irr",
        text: "LinkedIn",
      },
      {
        social: "facebook",
        imageUrl: "/icons/facebook.svg",
        link: "https://t.me/pounes_irr",
        text: "Facebook",
      },
      {
        social: "clubhouse",
        imageUrl: "/icons/clubhouse.svg",
        link: "https://t.me/pounes_irr",
        text: "Clubhouse",
      },
      {
        social: "twitch",
        imageUrl: "/icons/twitch.svg",
        link: "https://t.me/pounes_irr",
        text: "Twitch",
      },
      {
        social: "patreon",
        imageUrl: "/icons/patreon.svg",
        link: "https://t.me/pounes_irr",
        text: "Patreon",
      },
      {
        social: "pinterest",
        imageUrl: "/icons/pinterest.svg",
        link: "https://t.me/pounes_irr",
        text: "Pinterest",
      },
      {
        social: "tiktok",
        imageUrl: "/icons/tiktok.svg",
        link: "https://t.me/pounes_irr",
        text: "TikTok",
      },
      {
        social: "rubika",
        imageUrl: "/icons/rubika.png",
        link: "https://instagram.com/pounes.ir",
        text: "Rubika",
      },
      {
        social: "anker",
        imageUrl: "/icons/anker.png",
        link: "https://t.me/pounes_irr",
        text: "Anker",
      },
      {
        social: "applemusic",
        imageUrl: "/icons/applemusic.svg",
        link: "https://t.me/pounes_irr",
        text: "Apple Music",
      },
      {
        social: "breaker",
        imageUrl: "/icons/breaker.svg",
        link: "https://t.me/pounes_irr",
        text: "Breaker",
      },
      {
        social: "castbox",
        imageUrl: "/icons/castbox.svg",
        link: "https://t.me/pounes_irr",
        text: "Castbox",
      },
      {
        social: "googlepodcast",
        imageUrl: "/icons/googlepodcast.svg",
        link: "https://t.me/pounes_irr",
        text: "Google Podcast",
      },
      {
        social: "itunes",
        imageUrl: "/icons/itunes.svg",
        link: "https://t.me/pounes_irr",
        text: "iTunes",
      },
      {
        social: "applepodcast",
        imageUrl: "/icons/applepodcast.svg",
        link: "https://t.me/pounes_irr",
        text: "Apple Podcast",
      },
      {
        social: "overcast",
        imageUrl: "/icons/overcast.svg",
        link: "https://t.me/pounes_irr",
        text: "Overcast",
      },
      {
        social: "pocketcasts",
        imageUrl: "/icons/pocketcasts.svg",
        link: "https://t.me/pounes_irr",
        text: "Pocket Casts",
      },
      {
        social: "podbean",
        imageUrl: "/icons/podbean.svg",
        link: "https://t.me/pounes_irr",
        text: "Podbean",
      },
      {
        social: "radiopublic",
        imageUrl: "/icons/radiopublic.svg",
        link: "https://t.me/pounes_irr",
        text: "Radio Public",
      },
      {
        social: "soundcloud",
        imageUrl: "/icons/soundcloud.svg",
        link: "https://instagram.com/pounes.ir",
        text: "SoundCloud",
      },
      {
        social: "spotify",
        imageUrl: "/icons/spotify.svg",
        link: "https://t.me/pounes_irr",
        text: "Spotify",
      },
      {
        social: "stitcher",
        imageUrl: "/icons/stitcher.svg",
        link: "https://t.me/pounes_irr",
        text: "Stitcher",
      },
      {
        social: "bazar",
        imageUrl: "/icons/bazar.svg",
        link: "https://t.me/pounes_irr",
        text: "Bazar",
      },
      {
        social: "googleplay",
        imageUrl: "/icons/googleplay.svg",
        link: "https://t.me/pounes_irr",
        text: "Google Play",
      },
      {
        social: "applestore",
        imageUrl: "/icons/applestore.svg",
        link: "https://t.me/pounes_irr",
        text: "Apple Store",
      },
      {
        social: "micet",
        imageUrl: "/icons/micet.svg",
        link: "https://t.me/pounes_irr",
        text: "Myket",
      },
      {
        social: "iapps",
        imageUrl: "/icons/iapps.svg",
        link: "https://t.me/pounes_irr",
        text: "iApps",
      },
      {
        social: "sibapp",
        imageUrl: "/icons/sibapp.svg",
        link: "https://t.me/pounes_irr",
        text: "SibApp",
      },
      {
        social: "dribble",
        imageUrl: "/icons/dribble.svg",
        link: "https://t.me/pounes_irr",
        text: "Dribbble",
      },
      {
        social: "behance",
        imageUrl: "/icons/behance.svg",
        link: "https://t.me/pounes_irr",
        text: "Behance",
      },
    ],
  },
  {
    id: 2,
    type: "call",
    text: "Call & Contact Methods",
    blocks: [
      {
        type: "tell",
        imageUrl: "/icons/mobile.svg",
        link: "09224883894",
        text: "My Mobile Number",
      },
      {
        type: "phoneNumber",
        imageUrl: "/icons/phone.svg",
        link: "https://t.me/pounes_irr",
        text: "Landline",
      },
      {
        type: "email",
        imageUrl: "/icons/email.svg",
        link: "abolfazl021mokhtari@gmail.com",
        text: "My Email",
      },
      {
        type: "sms",
        imageUrl: "/icons/sms.svg",
        link: "09224883894",
        text: "Send SMS",
      },
    ],
  },
  {
    id: 3,
    type: "slider",
    text: "My Products",
    blocks: [
      {
        imageUrl: "/images/visitCard.png",
        link: "09224883894",
        title: "Shopping Cart",
        description: "Price is fixed",
        text: "My Mobile Number",
      },
      {
        imageUrl: "/images/visitCard.png",
        link: "09224883894",
        title: "Shopping Cart",
        description: "Price is fixed",
        text: "My Mobile Number",
      },
      {
        imageUrl: "/images/visitCard.png",
        link: "09224883894",
        title: "Shopping Cart",
        description: "Price is fixed",
        text: "My Mobile Number",
      },
    ],
  },
  {
    id: 4,
    type: "banner",
    text: "My Banner",
    imageUrl: "/images/visitCard.png",
    link: "https://pounes.ir",
  },
  {
    id: 5,
    type: "video",
    text: "My Video",
    videoUrl: "https://www.aparat.com/v/IN6Jp?discovery=1",
  },
  {
    id: 6,
    type: "link",
    text: "My Links",
    blocks: [
      {
        link: "09224883894",
        text: "My Mobile Number 2",
      },
      {
        link: "09224883894",
        text: "My Mobile Number",
      },
      {
        link: "09224883894",
        text: "My Mobile Number 3",
      },
    ],
  },
  {
    id: 7,
    type: "superlink",
    text: "My Links",
    blocks: [
      {
        link: "09224883894",
        text: "My Phone Number 2",
        description: "Description of this link",
      },
      {
        link: "09224883894",
        text: "My Phone Number, Description of this link, Description of this link, Description of this link, Description of this link, Description of this link, Description of this link",
        description:
          "Description of this link, Description of this link, Description of this link, Description of this link, Description of this link, Description of this link, Description of this link, Description of this link, Description of this link",
      },
      {
        link: "09224883894",
        text: "My Phone Number 3",
        description: "Description of this link",
      },
    ],
  },
  {
    id: 8,
    type: "map",
    text: "My Routes",
    blocks: [
      {
        type: "neshan",
        link: "09224883894",
        text: "Navigate with Neshan",
      },
      {
        type: "balad",
        link: "09224883894",
      },
    ],
  },
  {
    id: 9,
    type: "text",
    text: "Welcome to the Pouns Educational Website.",
    size: "3",
    align: "right",
  },
  {
    id: 10,
    type: "question",
    blocks: [
      {
        id: 1,
        question: "Welcome to the Pouns Educational Website.",
        answer: "Welcome to the Pouns Educational Website.",
      },
      {
        id: 2,
        question: "Welcome to the Pouns Educational Website.",
        answer: "Welcome to the Pouns Educational Website.",
      },
    ],
  },
  {
    id: 11,
    type: "payment",
    text: "Payment Links",
    blocks: [
      {
        text: "Pay, pay, pay, pay, pay, pay, pay, pay",
        link: "Welcome to the Pouns Educational Website.",
      },
      {
        text: "Pay",
        link: "Welcome to the Pouns Educational Website.",
      },
    ],
  },
];
